###CalculateHealth (POST)
POST http://localhost:3000/api/bonsais/calculate
Content-Type: application/json

[
  {
    "bonsai_id": 1,
    "name": "Oscar",
    "surname": "Cobo",
    "points": [5, 6, 7, 8, 9]
  },
  {
    "bonsai_id": 2,
    "name": "Silvia",
    "surname": "Cobo",
    "points": [5, 5, 4, 4, 6]
  },
  {
    "bonsai_id": 3,
    "name": "Manuel",
    "surname": "Cobo",
    "points": [4, 2, 2, 10, 7]
  }
]